group 'com.taobao.power_image'
version '1.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 21

        // ndk {
        //     // ABIs you want .so files for
        //     abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
        // }

        // externalNativeBuild {
        //     cmake {
        //         cppFlags "-std=c++17 -fexceptions -frtti"
        //     }
        // }

        
    }
    lintOptions {
        disable 'InvalidPackage'
    }

    // externalNativeBuild {
    //     cmake {
    //         path "src/main/cpp/CMakeLists.txt"
    //         version "4.1.1"
    //     }
    // }
}
